server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name: quora-api

  datasource:
    url: jdbc:postgresql://localhost:5432/quora
    username: postgres
    password: admin
    platform: postgres
    driverclassName: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: postgresql